export const projects = [
    {
        id :1,
        name:"password generator",
        thumbnail: "#",
        status: "active",
        techCategory: "web",
        catogary: "biginner",
        description:" unique variable password generator",
        techstack: ["react.js","CSS"],
        gitHubRepo:"#",
        Hosting:"#",
    },
    {
        id :2,
        name:"Todo list",
        thumbnail: "./images/project images/todoImg.png",
        status: "active",
        techCategory: "web",
        catogary: "biginner",
        description:" a simple todo app with crud operation. It also stores the todo creation time \
                    and provides the on-place update feature",
        techstack: ["HTML","CSS","JavaScript"],
        gitHubRepo:"#",
        Hosting:"#",
    },
    {
        id :3,
        name:"simple calculator",
        thumbnail: "./images/project images/calculatorImg.png",
        status: "active",
        techCategory: "web",
        catogary: "biginner",
        description:" simple calculator for basic airthmatic operation",
        techstack: ["HTML","CSS","JavaScript"],
        gitHubRepo:"#",
        Hosting:"#",
    },
    
]