export const skills = [
  { name: "C", logo: "./logos/tech logos/c.svg", catagory: "Languages", proficiency: 90 },
  { name: "C++", logo: "./logos/tech logos/cpp.svg", catagory: "Languages", proficiency: 85 },
  { name: "Java", logo: "./logos/tech logos/java.svg", catagory: "Languages", proficiency: 85 },
  { name: "pyhton", logo: "./logos/tech logos/python.svg", catagory: "Languages", proficiency: 85 },
  { name: "HTML", logo: "./logos/tech logos/html.svg", catagory: "Frontend", proficiency: 90 },
  { name: "CSS", logo: "./logos/tech logos/css.svg", catagory: "Frontend", proficiency: 85 },
  { name: "JavaScript", logo: "./logos/tech logos/javascript.svg", catagory: "Frontend", proficiency: 80 },
  { name: "React", logo: "./logos/tech logos/react.svg", catagory: "Frontend", proficiency: 75 },
  { name: "Tailwind", logo: "./logos/tech logos/tailwind.svg", catagory: "Frontend", proficiency: 75 },
  { name: "Node.js", logo: "./logos/tech logos/nodejs.svg", catagory: "Backend", proficiency: 75 },
  { name: "Express.js", logo: "./logos/tech logos/express.svg", catagory: "Backend", proficiency: 70 },
  { name: "Mongo DB", logo: "./logos/tech logos/mongodb.svg", catagory: "Backend", proficiency: 70 },
  { name: "Git", logo: "./logos/tech logos/git.svg", catagory: "Tools & others", proficiency: 60 },
  { name: "GitHub", logo: "./logos/tech logos/github.svg", catagory: "Tools & others", proficiency: 80 },
  { name: "Postman", logo: "./logos/tech logos/postman.svg", catagory: "Tools & others", proficiency: 60 },
  { name: "REST api", logo: "./logos/tech logos/restAPI.svg", catagory: "Tools & others", proficiency: 70 },
];